const mobileProducts = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    model: "A3104",
    price: 999,
    available: "buy",
    brand: "Apple",
    color: [
      "Natural Titanium",
      "Blue Titanium",
      "White Titanium",
      "Black Titanium",
    ],
  },
  {
    id: 2,
    name: "Samsung Galaxy S24 Ultra",
    model: "SM-S928",
    price: 1299,
    available: "buy",
    brand: "Samsung",
    color: [
      "Titanium Gray",
      "Titanium Black",
      "Titanium Violet",
      "Titanium Yellow",
    ],
  },
  {
    id: 3,
    name: "Google Pixel 8 Pro",
    model: "G8PRO",
    price: 899,
    available: "sold",
    brand: "Google",
    color: ["Obsidian", "Porcelain", "Bay", "Hazel"],
  },
  {
    id: 4,
    name: "OnePlus 12",
    model: "CPH2581",
    price: 799,
    available: "buy",
    brand: "OnePlus",
    color: ["Silky Black", "Flowy Emerald", "Marble Odyssey"],
  },
  {
    id: 5,
    name: "Xiaomi 14 Pro",
    model: "23116PN5BC",
    price: 949,
    available: "sold",
    brand: "Xiaomi",
    color: ["Black", "White", "Green", "Pink"],
  },
  {
    id: 6,
    name: "iPhone 14",
    model: "A2882",
    price: 699,
    available: "buy",
    brand: "Apple",
    color: ["Blue", "Purple", "Yellow", "Midnight", "Starlight"],
  },
  {
    id: 7,
    name: "Samsung Galaxy Z Flip5",
    model: "SM-F731B",
    price: 999,
    available: "sold",
    brand: "Samsung",
    color: ["Mint", "Graphite", "Cream", "Lavender", "Gray"],
  },
  {
    id: 8,
    name: "Nothing Phone 2",
    model: "AIN065",
    price: 599,
    available: "buy",
    brand: "Nothing",
    color: ["White", "Dark Gray", "Blue"],
  },
  {
    id: 9,
    name: "Asus ROG Phone 8",
    model: "AI2401",
    price: 1099,
    available: "buy",
    brand: "Asus",
    color: ["Phantom Black", "Rebel Gray", "Storm White"],
  },
  {
    id: 10,
    name: "Vivo X100 Pro",
    model: "V2307",
    price: 899,
    available: "sold",
    brand: "Vivo",
    color: ["Starry Blue", "Sunset Orange", "Asteroid Black"],
  },
  {
    id: 11,
    name: "Oppo Find X7 Ultra",
    model: "CPH2525",
    price: 1199,
    available: "buy",
    brand: "Oppo",
    color: ["Ocean Blue", "Desert Brown", "Sepia Black"],
  },
  {
    id: 12,
    name: "Motorola Edge 40",
    model: "XT2303-4",
    price: 599,
    available: "sold",
    brand: "Motorola",
    color: ["Nebula Green", "Lunar Blue", "Solar Gold", "Eclipse Black"],
  },
];

// {
//   name: "Google Pixel 8 Pro",
//   model: "G8PRO",
//   price: 899,
//   available: "sold",
//   brand: "Google",
// }

export default mobileProducts;
